[package]
authors = ["Mike Cargal <mike@cargal.net>"]
edition = "2018"
name = "dungeoncrawl"
version = "0.1.0"
[dependencies]
bracket-lib = "0.8.1"
legion = "=0.3.0"
colored = "2"
lazy_static = "1.4.0"